# Generated by Django 3.2.6 on 2021-10-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serapp', '0002_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='room',
        ),
    ]
