# Generated by Django 3.2.6 on 2021-10-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serapp', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='arz_roo_boors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timeclosed', models.DateTimeField()),
                ('market_cap', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='room',
        ),
    ]
