# Generated by Django 3.2.6 on 2021-11-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serapp', '0005_auto_20211030_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_arz',
            name='market_cap',
            field=models.FloatField(),
        ),
    ]
